version: "3"

services:
  empire-weatherman:
    build: .
    image: empire-weatherman
    stdin_open: true
    tty: true
    restart: "unless-stopped"
    volumes:
      - ./state/:/app/state/
    environment:
      SEASONS: '[["Recent_history", "mw-content-text"]]'
      TTS_SEASON_JSON_DIR: "/app/tts/"
      ARTICLES_JSON: "/app/state/articles.json"
      SUMMARIZE: "True"
      OPENAI_API_MODEL: "gpt-4.1"
